<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="shbudipa" name="com.pld.restassured.dashboard.AttritionAPI" tests="4" failures="1" timestamp="24 May 2019 11:29:28 GMT" time="77.115" errors="0">
  <testcase name="verifyAttritionLossReason" time="24.306" classname="com.pld.restassured.dashboard.AttritionAPI"/>
  <testcase name="verifyAttritionAsOFTest" time="20.900" classname="com.pld.restassured.dashboard.AttritionAPI"/>
  <testcase name="verifyAttritionBybandTest" time="29.462" classname="com.pld.restassured.dashboard.AttritionAPI"/>
  <testcase name="verifyAnnualizedRatesAndVoluntaryLosses" time="2.447" classname="com.pld.restassured.dashboard.AttritionAPI">
    <failure type="org.json.JSONException" message="JSONObject[&quot;VOL_LOSSES&quot;] is not an int.">
      <![CDATA[org.json.JSONException: JSONObject["VOL_LOSSES"] is not an int.
	at org.json.JSONObject.getInt(JSONObject.java:603)
	at com.pld.restassured.dashboard.AttritionAPI.verifyAnnualizedRatesAndVoluntaryLosses(AttritionAPI.java:172)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyAnnualizedRatesAndVoluntaryLosses -->
</testsuite> <!-- com.pld.restassured.dashboard.AttritionAPI -->
